### PR TITLE
Add a linter to validate external links

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR):
- Adds a plugin [remark-lint-no-dead-urls](https://github.com/remarkjs/remark-lint-no-dead-urls) to ensure that external URLs in Markdown pages are working. The linter returns warnings on https://www.php.net/ on working links in some reason (I assume server related issues) so I excluded this domain in the configuration.
- Replaces or removes dead links

Internal ticket: COMDOX-156

## Test

[Failed validate job](https://github.com/AdobeDocs/commerce-testing/actions/runs/6948160793/job/18903522012#step:11:12) reporting about dead links.

### CODE REVIEW

**Comment by dshevtsov** [comment]
@jeff-matthews please see a [report](https://github.com/AdobeDocs/commerce-php/actions/runs/6949632907/job/18908145518?pr=215) and fix the links.

**Comment by jeff-matthews** [comment]
Will do @dshevtsov. I'll push directly to this branch unless you say otherwise.

Also, just an FYI that when I run `yarn test` locally with the new config, I get a bunch of offline warnings:

```
...
src/pages/tutorials/index.md
              1:1  warning  You are not online and have not set skipOffline: true.                                                                                                                 no-dead-urls  remark-lint

⚠ 512 warnings
``` 

I don't know why, but maybe adding the `skipOffline` option would help. It would be nice to be able to run locally without the noise.

**Comment by jeff-matthews** [comment]
Commit [d8da865](https://github.com/AdobeDocs/commerce-php/pull/215/commits/d8da865dafc300434ac2f4aabc9434c6be8dec78) reduced the warning count from 58 to 19.

All but two of the remaining 19 are located in MRG files, which I'm reluctant to fix since the source comes from READMEs in code base repos. Fixing them here will only be temporary. The test fill start failing again when we regenerate the MRG files from source unless we fix the links in the source READMEs.

@dshevtsov, how do you want to proceed for MRG files?

**Comment by dshevtsov** [comment]
I cannot reproduce the issue with `You are not online and have not set skipOffline: true.`
I tried both with and without VPN. 

As a project owner you are good to go for any changes in the config that work for you.

Any changes to MRG have to be ported to the codebase.

**Comment by dshevtsov** [comment]
I noticed that with and without VPN return different results. It appears that when I run the test without VPN, my Internet provider blocks the _excessive outgoing connections_.

**Comment by jeff-matthews** [comment]
Local testing is inconsistent with the latest [validation run](https://github.com/AdobeDocs/commerce-php/actions/runs/6959620252/job/18937262413?pr=215).

Local testing produces no warnings, but latest validation run produces two warnings. I suspect it has something to do with caching as mentioned in the plugin README:

```
[check-links](https://github.com/transitive-bullshit/check-links) memoizes results, so on any given run each URL will only be pinged once; subsequent checks will be returned from the cache.
```

I'm not sure where the cache lives though. Maybe somewhere in the `node_modules` directory.

Anyway, I'll fix the two remaining warnings in the MRG and hopefully the validation run will pass.

**Review by jeff-matthews — APPROVED** [review]

**Pull request merged**
