### PR TITLE
Replace obsolete devdocs links

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) replaces links to `https://devdocs.magento.com` topics that have already been migrated to the Adobe Devsite (`https://developer.adobe.com`).

## Affected pages

- See changed files

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My changes follow the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by meker12 — COMMENTED** [review]
RE: Changes in the Module Reference Guide:  Since the content in this guide is auto-generated from the Readme files in the code repos, I believe the link updates in this PR will be overwritten the next time the guide is generated.

**Review by meker12 — APPROVED** [review]
RE: Changes in the Module Reference Guide: Since the content in this guide is auto-generated from the Readme files in the code repos, I believe the link updates in this PR will be overwritten the next time the guide is generated.

Also noticed that the Module Reference is missing from the Commerce PHP index page.

**Comment by jeff-matthews** [comment]
Doh! Good catch @meker12. Since I already made the effort and it would take more time to revert than I think it's worth, I'm going to leave them as-is and let them be overwritten next release.

However, I will push a change for adding the Module Reference Guide to the main landing page and then re-request your review.

**Comment by jeff-matthews** [comment]
Oops, looks like your approval just now triggered the auto-merge.

**Pull request merged**
