### PR TITLE
Update Backward incompatible changes reference reports

### PR DESCRIPTION
**Pull request by devops-devdocs**
2.4.7-2.4.7-p1 [Backward incompatible changes reference](https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/reference/) docs.

Preview: https://commerce-docs.github.io/commerce-php/development/backward-incompatible-changes/reference/

### CODE REVIEW

**Comment by dshevtsov** [comment]
[https://tools.ietf.org/](https://tools.ietf.org/html/rfc2119) links are temporarily unavailable due to maintenance work on the site.

**Review by jeff-matthews — COMMENTED** [review]
Historically, as far as I know we've never published BIC reference for security patches. We published some _highlight_ info related to 2.4.3-p1 and 2.4.3-p2, but that was a special request.

@chernenm, is it necessary to publish BIC reference for all security patches?

**Review by jeff-matthews — APPROVED** [review]

**Comment by hostep** [comment]
There is no way that the changes from Adobe Commerce are correct, I don't have access to that codebase, but it would be extremely surprising if so many classes and interfaces and blocks and what have you, got removed in a small patch release version...

**Comment by dshevtsov** [comment]
@hostep Looks like so. Thanks for the heads-up!

**Pull request merged**
