### PR TITLE
Add Module Reference Guide

### PR DESCRIPTION
**Pull request by dshevtsov**
## Purpose of this pull request

This pull request (PR) adds the Module Reference Guide generated using our internal automation.

## Affected pages

-  /module-reference/**

## Preview

https://adobedocs.github.io/commerce-php/module-reference/

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My changes follow the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, have you deployed this branch to  the staging environment or GH pages? If not, please do so. It doesn't matter which one. No one is using either environment right now.

**Comment by dshevtsov** [comment]
@jeff-matthews I found how to exclude files for linting. Do you know how to exclude likes for link checking?

**Comment by dshevtsov** [comment]
> have you deployed this branch to the staging environment or GH pages?
I don't know how to do this.

**Comment by dshevtsov** [comment]
Now it [fails](https://github.com/AdobeDocs/commerce-php/runs/6762144674?check_suite_focus=true#step:7:32) on a build stage, because of a 404 image linked from a Readme.

**Comment by dshevtsov** [comment]
I assume the only way to handle this is to fix the issues here and create accompanying PR to the codebase to avoid future failures.

**Comment by dshevtsov** [comment]
Re-generating the MRG guide, because the one that's been added was generated for 2.4.3.

**Comment by dshevtsov** [comment]
Squashed the commits locally

**Review by jeff-matthews — APPROVED** [review]
I didn't go through every single file, but a brief scan of the staging site looks good and checks are passing. Looks good @dshevtsov!

**Pull request merged**
