### PR TITLE
COMDOX-299: Migrate Backward-incompatible changes from magento/devdocs

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Purpose of this pull request

This pull request (PR) migrates the [Backward-incompatible changes](https://devdocs.magento.com/guides/v2.4/release-notes/backward-incompatible-changes/index.html) topics from the `devdocs.magento.com` site to the Adobe DevSite.

- **Staging**: https://developer-stage.adobe.com/commerce/php/development/backward-incompatible-changes/

## Affected pages

- Several

## Links to related PRs or Jira tickets

- COMDOX-299
- https://github.com/magento-commerce/devdocs/pull/3184

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My changes follow the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dshevtsov** [comment]
There is a bug with the rendering

Screen Shot 2022-10-10 at 2 09 18 PM

**Comment by dshevtsov** [comment]
I presume we should reconsider the format in the future.
- Convert source to data-based templates
- Convert tables to lists grouped by a type of change

Example:

h4. Class changes

Public methods added:
- class::method
- class::method

Protected properties added:
- class::property
- class::property

**Review by dshevtsov — APPROVED** [review]
Approving as the content meets parity with devdocs. I assume the future work to fix the rendering issue and reconsider formatting will be done in the future PRs.

**Comment by jeff-matthews** [comment]
Good suggestions @dshevtsov. Please feel free to create tickets to refactor the format in the future.  The bug you mentioned is a known issue (DEVSITE-281).

**Pull request merged**
