### PR TITLE
ACP2E-1442: Update some misspellings in the documentation

### PR DESCRIPTION
**Pull request by veloraven**
1. [Frontend customization](https://developer.adobe.com/commerce/php/architecture/basics/frontend-customization/) - Admin Pattern library is fully marked as hyperlink in most places except one
2. [View Models](https://developer.adobe.com/commerce/php/development/components/view-models/#examples) - text is too close to horizontal line which makes it hard to read.

## Related Issue
[ACP2E-1442](https://jira.corp.adobe.com/browse/ACP2E-1442)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]
Thanks for the fixes @veloraven.

**Comment by jeff-matthews** [comment]
@veloraven, please sign the Adobe CLA so that I can merge your changes.

**Comment by veloraven** [comment]
@jeff-matthews done. Never needed it before for other repositories.

**Comment by jeff-matthews** [comment]
Thanks again @veloraven!

**Pull request merged**
