### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by GrzegorzWalewski**
Added spaces after application

## Purpose of this pull request

Added spaces after application

## Affected pages

-  https://developer.adobe.com/commerce/php/development/components/plugins/

## Checklist:

- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My changes follow the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Thanks for the contribution @GrzegorzWalewski!

Please sign the Adobe CLA so I can get this merged and published.

**Comment by GrzegorzWalewski** [comment]
@jeff-matthews Adobe CLA signed ;)

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@GrzegorzWalewski , the CLA check still hasn't cleared... Are you sure you signed it?

**Comment by GrzegorzWalewski** [comment]
Done :D

**Pull request merged**
