### PR TITLE
fix reasons for incompatibility with Application server

### PR DESCRIPTION
**Pull request by andimov**
## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

### CODE REVIEW

**Review by jhadobe — APPROVED** [review]

**Comment by jhadobe** [comment]
@andimov please sign the [Details](https://github.com/AdobeDocs/commerce-php/pull/243/checks?check_run_id=22429852029).

**Comment by andimov** [comment]
> @andimov please sign the [Adobe CLA](https://github.com/AdobeDocs/commerce-php/pull/243/checks?check_run_id=22429852029).

done

**Comment by jhadobe** [comment]
@andimov is this change specific to the `2.4.7-beta3` release, or is this for the full `2.4.7` release next month?

**Comment by andimov** [comment]
@jhadobe I'm unsure whether this document has been published yet, but we need this PR delivered asap as it corrects an error in the documentation

**Pull request merged**
