### PR TITLE
Gendocs 2.4.6 beta2: MRG and BIC

### PR DESCRIPTION
**Pull request by dshevtsov**
## Description

Update data for the Backward-incompatible changes reference and the Module reference guide. Generated by automation using the 2.4.6-beta2 version.

Preview:
- BIC: https://adobedocs.github.io/commerce-php/development/backward-incompatible-changes/reference/
- MRG: https://adobedocs.github.io/commerce-php/module-reference/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dshevtsov** [comment]
A lot of Markdownlint violations in the imported Readmes.
I'm fixing them here and after that I will add the fixes to the codebase. Thinking on optimization of this flow.

**Comment by dshevtsov** [comment]
Even links to wiki.corp.adobe.com

**Comment by dshevtsov** [comment]
@jeff-matthews which approach should I use to generate preview here?

**Comment by jeff-matthews** [comment]
Please use the GitHub Pages staging environment. When satisfied and this PR is merged, we must deploy the 2.4.6-develop branch to the primary staging environment (`developer-stage.adobe.com`) for beta users.

**Review by jeff-matthews — COMMENTED** [review]
Nice naming convention for the include directives 😎

**Comment by dshevtsov** [comment]
I pushed `gendocs_2.4.6-beta2` to the upstream repo to be able to run the workflows for generating a preview.
Added preview links to the PR description.

**Review by jeff-matthews — APPROVED** [review]

**Comment by dshevtsov** [comment]
The `validate` check didn't run. I wonder if it's because the PR is created from a fork.

**Comment by dshevtsov** [comment]
The `validate` check didn't run. I wonder if it's because the PR is created from a fork.

**Comment by jeff-matthews** [comment]
Sometimes it gets stuck. The fork shouldn't matter because contributor PRs come from forks. Try pushing another commit or closing/re-opening the PR.

**Comment by dshevtsov** [comment]
I see, the corresponding workflow was configured to run on `main` only. I'll remove `validate` from the branch protection rules.

**Comment by dshevtsov** [comment]
Deployed `2.4.6-develop` to `developer-stage.adobe.com`.

**Pull request merged**
